### ISSUE TITLE
Profiling OpenFOAM

### ISSUE THREAD

**Issue by simomartini** [nerscadmin/IPM#28]
I'm trying to make OpenFoam profiling with IPM. But I found a mistake when I use ploticus.

This is what I get 

>
[smartini@login2 damBreak]$ /home/smartini/ipm_2.0.3/bin/ipm_parse -html smartini.1504091236.699412.ipm.xml
 data_acquire    = 0 sec
 data_workup     = 0 sec
  mpi_pie        = 0 sec
  task_data      = 0 sec
  load_bal       = 0 sec
  time_stack     = 0 sec
  mpi_stack      = 0 sec
  mpi_buff       = 0 sec
  switch+mem     = 0 sec
  topo_tables    = 0 sec
  topo_data      = 0 sec
  topo_time      = 0 sec
 html_all        = 0 sec
 html_regions    = 0 sec
pl proc areadef: error 100: y range is invalid .. likely culprit is yautorange or yrange
pl proc areadef: error 10: cannot set up plotting area .. likely culprits: bad xrange or yrange, or bad area rectangle
 html_nonregion  = 0 sec
>

I attached here my xml file 

[smartini.1504091236.699412.ipm.xml.zip](https://github.com/nerscadmin/IPM/files/1263369/smartini.1504091236.699412.ipm.xml.zip)

I tried to do the tests I found in ipm and they did not give me this problem.

Kind Regard 
Simone

**Comment by cdaley** [comment]
I think you are seeing the error because you have a "terse" log file. Please re-run your application with the environment setting `export IPM_LOG=full` to save detailed message count and size data in the IPM XML file. I think the plotting error is happening because there is no message size data in the file. I am able to run `ipm_parse` on your data file and successfully generate the plots which don't depend on the detailed message data, e.g. time_stack_byrank.png and mpi_pie.png.

Thanks, 
Chris

**Comment by simomartini** [comment]
Thanks for the query replay.
The problem where exactly this, with IPM_LOG=full I will get everything.

Kind Regards
Simone Martini

On 09 Sep 2017, at 00:28, cdaley <notifications@github.com<mailto:notifications@github.com>> wrote:


I think you are seeing the error because you have a "terse" log file. Please re-run your application with the environment setting export IPM_LOG=full to save detailed message count and size data in the IPM XML file. I think the plotting error is happening because there is no message size data in the file. I am able to run ipm_parse on your data file and successfully generate the plots which don't depend on the detailed message data, e.g. time_stack_byrank.png and mpi_pie.png.

Thanks,
Chris
