### ISSUE TITLE
fortran calls are accounted twice

### ISSUE THREAD

**Issue by ggouaillardet** [nerscadmin/IPM#9]
I tested IPM master with both openmpi and mpich, and wrote a simple fortran test program similar to tests/test.alltoall
IPM reports twice the number of calls to MPI_Alltoall (!)
the root cause is fortran pmpi_alltoall_ calls IPM MPI_Alltoall instead of the MPI PMPI_Alltoall symbol, __and__ IPM does nothing to avoid double accounting
fwiw, I asked the openmpi folks to comment at http://www.open-mpi.org/community/lists/devel/2015/08/17842.php since that issue can be solved within openmpi (I cannot speak for other MPI flavors, many of them being mpich derivatives)
imho, avoiding double accounting is pretty trivial to avoid in IPM __unless__ MPI_THREAD_MULTIPLE is used.

**Comment by swfrench** [comment]
Yes, indeed - somehow my earlier tests did not uncover this either, however it appears to be the case for both the latest OpenMPI and MPICH releases (I was using much older versions at the time).

Since IPM is not currently thread safe (no internal locks to support `MPI_THREAD_MULTIPLE`, nor explicit memory barriers to support `_SERIALIZED`), then adding a small flag to indicate whether we are already within a fortran `PMPI_*` routine, and thus whether to count an intercepted `MPI_*` binding, should be fairly simple.

I added this the other day to the `wrapper_improvements` topic branch (in addition to some experiments with weak symbols for the fortran `PMPI_*` bindings).

**Comment by swfrench** [comment]
I will merge some new code into master that should correct this issue shortly. It is part of a new effort to split the C and Fortran wrappers as discussed in the comments to commit 5901492.

**Comment by swfrench** [comment]
This should now be fixed in 48b3a70.
